# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com/customization/builds/
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    dir: cmd/rabtap
    goos:
      - linux
      - wasip1
      - darwin
      - windows
      - freebsd
      - openbsd
    goarch:
      - wasm
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: wasip1
        goarch: amd64
      - goos: wasipi
        goarch: arm
      - goos: wasipi
        goarch: arm64
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: openbsd
        goarch: arm64
      - goos: windows
        goarch: arm
archives:
  - files:
      - README.md
      - LICENSE
      - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
