---
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
      - GOTOOLCHAIN=auto
    ldflags:
      - -s -w
      - -X "main.BuildGoVersion={{.Env.GOVERSION}}"
      - -X "main.BuildCommit={{.FullCommit}}"
      - -X "main.BuildVersion={{.Tag}}"
      - -X "main.BuildDate={{.Date}}"
    dir: cmd/rabtap
    goos:
      - linux
      - wasip1
      - darwin
      - windows
      - freebsd
      - openbsd
    goarch:
      - wasm
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: wasip1
        goarch: amd64
      - goos: wasip1
        goarch: arm
      - goos: wasip1
        goarch: arm64
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: openbsd
        goarch: arm64
      - goos: windows
        goarch: arm
archives:
  - files:
      - README.md
      - LICENSE
      - CHANGELOG.md
    format_overrides:
      - goos: windows
        formats: ["zip"]
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'