version: '3'
services:
    toxiproxy:
        image: shopify/toxiproxy:latest
        ports:
          - 55672:55672
          - 8474:8474
    rabbitmq:
        image: rabbitmq:3.7-management-alpine
        ports:
          - 5672:5672
          - 15672:15672

