on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: run tests
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  test:
    runs-on: ubuntu-latest
    steps:
      - name: create certificates
        run: cd testdata/pki && ./mkcerts.sh
      - name: Run RabbitMQ
        run: cd inttest/rabbitmq && docker-compose up -d
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: wait for RabbitMQ becoming ready
        run:
          timeout 30 sh -c "while true; do curl http://guest:password@localhost:15672/api/exchanges/%2f/amq.topic && break || sleep 3; done"
      - name: Run tests
        run: make test
      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1.0.6
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
